<?php
//
// File generated by Dolibarr installer 5.0.8 on 28 Mars 2020
//
// Take a look at conf.php.example file for an example of conf.php file
// and explanations for all possibles parameters.
//
$dolibarr_main_url_root='http://app-7045c4d5-ba79-4fa5-a991-bfc2f969ed3b.cleverapps.io ';
$dolibarr_main_document_root='/home/bas/app_7045c4d5-ba79-4fa5-a991-bfc2f969ed3b/htdocs';
//$dolibarr_main_url_root_alt='/custom';
//$dolibarr_main_document_root_alt='/Users/anthonycaumond/Dev/cybele/dolibarr/htdocs/custom';
$dolibarr_main_data_root='/home/bas/app_7045c4d5-ba79-4fa5-a991-bfc2f969ed3b/documents';
$dolibarr_main_db_host='bamwv4bnune4xlv6b42i-mysql.services.clever-cloud.com';
$dolibarr_main_db_port='20366';
$dolibarr_main_db_name='bamwv4bnune4xlv6b42i';
$dolibarr_main_db_prefix='llx_';
$dolibarr_main_db_user='uxxmg3fwsr5ymjnr';
$dolibarr_main_db_pass='2PRkxqhcwUkAiu0cBzFq';
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='utf8';
$dolibarr_main_db_collation='utf8_general_ci';
// Authentication settings
$dolibarr_main_authentication='dolibarr';

//$dolibarr_main_demo='autologin,autopass';
// Security settings
$dolibarr_main_prod='0';
$dolibarr_main_force_https='0';
$dolibarr_main_restrict_os_commands='mysqldump, mysql, pg_dump, pgrestore';
$dolibarr_nocsrfcheck='0';
$dolibarr_main_cookie_cryptkey='d97ce91052ebf31d5e2c9913ca4c01ed';
$dolibarr_mailing_limit_sendbyweb='0';

//$dolibarr_lib_FPDF_PATH='';
//$dolibarr_lib_TCPDF_PATH='';
//$dolibarr_lib_FPDI_PATH='';
//$dolibarr_lib_TCPDI_PATH='';
//$dolibarr_lib_ADODB_PATH='';
//$dolibarr_lib_GEOIP_PATH='';
//$dolibarr_lib_NUSOAP_PATH='';
//$dolibarr_lib_PHPEXCEL_PATH='';
//$dolibarr_lib_ODTPHP_PATH='';
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP='';
//$dolibarr_js_CKEDITOR='';
//$dolibarr_js_JQUERY='';
//$dolibarr_js_JQUERY_UI='';
//$dolibarr_js_JQUERY_FLOT='';

//$dolibarr_font_DOL_DEFAULT_TTF='';
//$dolibarr_font_DOL_DEFAULT_TTF_BOLD='';
