<?php
//
// File generated by Dolibarr installer 5.0.8 on 28 Mars 2020
//
// Take a look at conf.php.example file for an example of conf.php file
// and explanations for all possibles parameters.
//
$dolibarr_main_url_root='http://'.getenv("APP_ID").".cleverapps.io ';
$dolibarr_main_document_root='/home/bas/'.getenv("APP_ID")."/htdocs';
$dolibarr_main_url_root_alt='/custom';
$dolibarr_main_document_root_alt='/home/bas/'.getenv("APP_ID")."/htdocs/custom';
$dolibarr_main_data_root='/home/bas/".getenv("APP_ID")."/documents';
$dolibarr_main_db_host=getenv("MYSQL_ADDON_HOST");
$dolibarr_main_db_port=getenv("MYSQL_ADDON_PORT");
$dolibarr_main_db_name=getenv("MYSQL_ADDON_DB");
$dolibarr_main_db_prefix='llx_';
$dolibarr_main_db_user=getenv("MYSQL_ADDON_USER");
$dolibarr_main_db_pass=getenv("MYSQL_ADDON_PASSWORD");
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='utf8';
$dolibarr_main_db_collation='utf8_general_ci';
// Authentication settings
$dolibarr_main_authentication='dolibarr';

//$dolibarr_main_demo='autologin,autopass';
// Security settings
$dolibarr_main_prod='0';
$dolibarr_main_force_https='0';
$dolibarr_main_restrict_os_commands='mysqldump, mysql, pg_dump, pgrestore';
$dolibarr_nocsrfcheck='0';
$dolibarr_main_cookie_cryptkey='d97ce91052ebf31d5e2c9913ca4c01ed';
$dolibarr_mailing_limit_sendbyweb='0';

//$dolibarr_lib_FPDF_PATH='';
//$dolibarr_lib_TCPDF_PATH='';
//$dolibarr_lib_FPDI_PATH='';
//$dolibarr_lib_TCPDI_PATH='';
//$dolibarr_lib_ADODB_PATH='';
//$dolibarr_lib_GEOIP_PATH='';
//$dolibarr_lib_NUSOAP_PATH='';
//$dolibarr_lib_PHPEXCEL_PATH='';
//$dolibarr_lib_ODTPHP_PATH='';
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP='';
//$dolibarr_js_CKEDITOR='';
//$dolibarr_js_JQUERY='';
//$dolibarr_js_JQUERY_UI='';
//$dolibarr_js_JQUERY_FLOT='';

//$dolibarr_font_DOL_DEFAULT_TTF='';
//$dolibarr_font_DOL_DEFAULT_TTF_BOLD='';
